[package]
name = "convers"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.41.0", features = ["full"] }
reqwest = { version = "0.12.8", features = ["json"] }
serde_json = "1.0.132"
